import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const achievements = [
  // ==================== ROUNDS BADGES ====================
  {
    code: 'first_round',
    name: 'First Swing',
    description: 'Complete your first round',
    icon: '🏌️',
    category: 'rounds',
    points: 10,
    threshold: 1,
    sortOrder: 1,
  },
  {
    code: 'rounds_5',
    name: 'Getting Started',
    description: 'Complete 5 rounds',
    icon: '📅',
    category: 'rounds',
    points: 20,
    threshold: 5,
    sortOrder: 2,
  },
  {
    code: 'rounds_10',
    name: 'Regular Golfer',
    description: 'Complete 10 rounds',
    icon: '🥈',
    category: 'rounds',
    points: 30,
    threshold: 10,
    sortOrder: 3,
  },
  {
    code: 'rounds_25',
    name: 'Dedicated Player',
    description: 'Complete 25 rounds',
    icon: '🥇',
    category: 'rounds',
    points: 50,
    threshold: 25,
    sortOrder: 4,
  },
  {
    code: 'rounds_50',
    name: 'Golf Addict',
    description: 'Complete 50 rounds',
    icon: '🏆',
    category: 'rounds',
    points: 100,
    threshold: 50,
    sortOrder: 5,
  },
  {
    code: 'rounds_100',
    name: 'Golf Legend',
    description: 'Complete 100 rounds',
    icon: '👑',
    category: 'rounds',
    points: 200,
    threshold: 100,
    sortOrder: 6,
  },

  // ==================== SCORING BADGES (18 Holes) ====================
  {
    code: 'under_100_18',
    name: 'Century Breaker',
    description: 'Score under 100 on 18 holes',
    icon: '💯',
    category: 'scoring',
    points: 15,
    holesRequired: 18,
    threshold: 99,
    sortOrder: 10,
  },
  {
    code: 'under_90_18',
    name: 'Breaking 90',
    description: 'Score under 90 on 18 holes',
    icon: '🎯',
    category: 'scoring',
    points: 30,
    holesRequired: 18,
    threshold: 89,
    sortOrder: 11,
  },
  {
    code: 'under_80_18',
    name: 'Elite Golfer',
    description: 'Score under 80 on 18 holes',
    icon: '💎',
    category: 'scoring',
    points: 60,
    holesRequired: 18,
    threshold: 79,
    sortOrder: 12,
  },
  {
    code: 'par_18',
    name: 'Par Master',
    description: 'Shoot par or better on 18 holes',
    icon: '⭐',
    category: 'scoring',
    points: 100,
    holesRequired: 18,
    threshold: 72,
    sortOrder: 13,
  },

  // ==================== SCORING BADGES (9 Holes) ====================
  {
    code: 'under_50_9',
    name: 'Half Century',
    description: 'Score under 50 on 9 holes',
    icon: '🔥',
    category: 'scoring',
    points: 15,
    holesRequired: 9,
    threshold: 49,
    sortOrder: 20,
  },
  {
    code: 'under_45_9',
    name: 'Sharp Shooter',
    description: 'Score under 45 on 9 holes',
    icon: '🎯',
    category: 'scoring',
    points: 30,
    holesRequired: 9,
    threshold: 44,
    sortOrder: 21,
  },
  {
    code: 'under_40_9',
    name: 'Nine Hole Master',
    description: 'Score under 40 on 9 holes',
    icon: '💎',
    category: 'scoring',
    points: 60,
    holesRequired: 9,
    threshold: 39,
    sortOrder: 22,
  },

  // ==================== BIRDIE BADGES ====================
  {
    code: 'first_birdie',
    name: 'First Birdie',
    description: 'Score a birdie on any hole',
    icon: '🐦',
    category: 'birdies',
    points: 15,
    threshold: 1,
    sortOrder: 80,
  },
  {
    code: 'birdie_hunter',
    name: 'Birdie Hunter',
    description: 'Score 5 birdies total',
    icon: '🦅',
    category: 'birdies',
    points: 25,
    threshold: 5,
    sortOrder: 81,
  },
  {
    code: 'birdie_bonanza',
    name: 'Birdie Bonanza',
    description: 'Score 10 birdies total',
    icon: '🦃',
    category: 'birdies',
    points: 30,
    threshold: 10,
    sortOrder: 82,
  },
  {
    code: 'birdie_master',
    name: 'Birdie Master',
    description: 'Score 25 birdies total',
    icon: '🦚',
    category: 'birdies',
    points: 50,
    threshold: 25,
    sortOrder: 83,
  },
  {
    code: 'birdie_king',
    name: 'Birdie King',
    description: 'Score 50 birdies total',
    icon: '👑',
    category: 'birdies',
    points: 80,
    threshold: 50,
    sortOrder: 84,
  },
  {
    code: 'birdie_streak',
    name: 'Birdie Streak',
    description: 'Score birdies on 2 consecutive holes',
    icon: '🔥',
    category: 'birdies',
    points: 25,
    sortOrder: 85,
  },

  // ==================== PAR BADGES ====================
  {
    code: 'first_par',
    name: 'First Par',
    description: 'Score a par on any hole',
    icon: '⛳',
    category: 'pars',
    points: 10,
    threshold: 1,
    sortOrder: 90,
  },
  {
    code: 'par_collector',
    name: 'Par Collector',
    description: 'Score 10 pars total',
    icon: '📋',
    category: 'pars',
    points: 15,
    threshold: 10,
    sortOrder: 91,
  },
  {
    code: 'par_machine',
    name: 'Par Machine',
    description: 'Score 25 pars total',
    icon: '⚙️',
    category: 'pars',
    points: 25,
    threshold: 25,
    sortOrder: 92,
  },
  {
    code: 'steady_eddy',
    name: 'Steady Eddy',
    description: 'Complete a round at exactly par',
    icon: '⚖️',
    category: 'pars',
    points: 40,
    sortOrder: 93,
  },
  {
    code: 'par_streak',
    name: 'Par Streak',
    description: 'Score 3 pars in a row',
    icon: '🔗',
    category: 'pars',
    points: 25,
    sortOrder: 94,
  },
  {
    code: 'par_perfect',
    name: 'Par Perfect',
    description: 'Score 5 pars in a row',
    icon: '✨',
    category: 'pars',
    points: 50,
    sortOrder: 95,
  },

  // ==================== COURSES BADGES ====================
  {
    code: 'courses_3',
    name: 'Explorer',
    description: 'Play at 3 different courses',
    icon: '🗺️',
    category: 'courses',
    points: 20,
    threshold: 3,
    sortOrder: 30,
  },
  {
    code: 'courses_5',
    name: 'Traveler',
    description: 'Play at 5 different courses',
    icon: '✈️',
    category: 'courses',
    points: 40,
    threshold: 5,
    sortOrder: 31,
  },
  {
    code: 'courses_10',
    name: 'Moroccan Tour',
    description: 'Play at 10 different courses',
    icon: '🇲🇦',
    category: 'courses',
    points: 80,
    threshold: 10,
    sortOrder: 32,
  },
  {
    code: 'home_course',
    name: 'Home Course Hero',
    description: 'Play 5 rounds at the same course',
    icon: '🏠',
    category: 'courses',
    points: 25,
    threshold: 5,
    sortOrder: 33,
  },

  // ==================== TOURNAMENT BADGES ====================
  {
    code: 'first_tournament',
    name: 'Tournament Rookie',
    description: 'Enter your first tournament',
    icon: '🏟️',
    category: 'tournaments',
    points: 15,
    threshold: 1,
    sortOrder: 40,
  },
  {
    code: 'tournaments_3',
    name: 'Tournament Regular',
    description: 'Enter 3 tournaments',
    icon: '🎖️',
    category: 'tournaments',
    points: 30,
    threshold: 3,
    sortOrder: 41,
  },
  {
    code: 'tournaments_5',
    name: 'Competition Lover',
    description: 'Enter 5 tournaments',
    icon: '🏅',
    category: 'tournaments',
    points: 50,
    threshold: 5,
    sortOrder: 42,
  },
  {
    code: 'podium_finish',
    name: 'Podium Finish',
    description: 'Finish in top 3 of a tournament',
    icon: '🥉',
    category: 'tournaments',
    points: 60,
    sortOrder: 43,
  },
  {
    code: 'tournament_winner',
    name: 'Champion',
    description: 'Win a tournament',
    icon: '🏆',
    category: 'tournaments',
    points: 100,
    sortOrder: 44,
  },

  // ==================== HANDICAP BADGES ====================
  {
    code: 'handicap_improve_3',
    name: 'On the Rise',
    description: 'Lower your handicap by 3 strokes',
    icon: '📈',
    category: 'handicap',
    points: 30,
    threshold: 3,
    sortOrder: 50,
  },
  {
    code: 'handicap_improve_5',
    name: 'Major Improvement',
    description: 'Lower your handicap by 5 strokes',
    icon: '🎯',
    category: 'handicap',
    points: 50,
    threshold: 5,
    sortOrder: 51,
  },
  {
    code: 'single_digit',
    name: 'Single Digit',
    description: 'Reach single-digit handicap (under 10)',
    icon: '🌟',
    category: 'handicap',
    points: 80,
    threshold: 9,
    sortOrder: 52,
  },

  // ==================== PROFILE BADGES ====================
  {
    code: 'profile_complete',
    name: 'Profile Complete',
    description: 'Add name, city, and country',
    icon: '📝',
    category: 'profile',
    points: 10,
    sortOrder: 100,
  },
  {
    code: 'photo_added',
    name: 'Photo Added',
    description: 'Upload a profile photo',
    icon: '📷',
    category: 'profile',
    points: 15,
    sortOrder: 101,
  },
  {
    code: 'handicap_set',
    name: 'Handicap Set',
    description: 'Set your handicap',
    icon: '🎯',
    category: 'profile',
    points: 15,
    sortOrder: 102,
  },
  {
    code: 'first_club',
    name: 'First Club',
    description: 'Add your first club to My Bag',
    icon: '🏌️',
    category: 'profile',
    points: 10,
    sortOrder: 103,
  },
  {
    code: 'bag_ready',
    name: 'Bag Ready',
    description: 'Add 5+ clubs to My Bag',
    icon: '🎒',
    category: 'profile',
    points: 10,
    threshold: 5,
    sortOrder: 104,
  },

  // ==================== ON-COURSE BADGES ====================
  {
    code: 'fairway_finder',
    name: 'Fairway Finder',
    description: 'Hit 10 fairways total',
    icon: '🏌️',
    category: 'oncourse',
    points: 15,
    threshold: 10,
    sortOrder: 110,
  },
  {
    code: 'green_machine',
    name: 'Green Machine',
    description: 'Hit 10 greens in regulation',
    icon: '🏌️',
    category: 'oncourse',
    points: 15,
    threshold: 10,
    sortOrder: 111,
  },
  {
    code: 'bogey_free_9',
    name: 'Bogey Free 9',
    description: 'Complete 9 holes without a bogey',
    icon: '🛡️',
    category: 'oncourse',
    points: 25,
    sortOrder: 112,
  },

  // ==================== FAIRWAY BADGES ====================
  {
    code: 'fairway_5_round',
    name: 'Fairway Sharp',
    description: 'Hit 5 fairways in a single round',
    icon: '🎯',
    category: 'fairway',
    points: 10,
    threshold: 5,
    sortOrder: 113,
  },
  {
    code: 'fairway_10_round',
    name: 'Fairway Master',
    description: 'Hit 10 fairways in a single round',
    icon: '🏆',
    category: 'fairway',
    points: 25,
    threshold: 10,
    sortOrder: 114,
  },

  // ==================== GIR (GREEN IN REGULATION) BADGES ====================
  {
    code: 'gir_5_round',
    name: 'GIR Ace',
    description: 'Hit 5 greens in regulation in a single round',
    icon: '🟢',
    category: 'gir',
    points: 10,
    threshold: 5,
    sortOrder: 115,
  },
  {
    code: 'gir_10_round',
    name: 'GIR Pro',
    description: 'Hit 10 greens in regulation in a single round',
    icon: '💎',
    category: 'gir',
    points: 25,
    threshold: 10,
    sortOrder: 116,
  },
  {
    code: 'gir_18_round',
    name: 'GIR Perfect',
    description: 'Hit all 18 greens in regulation in a single round',
    icon: '🌟',
    category: 'gir',
    points: 50,
    threshold: 18,
    sortOrder: 117,
  },

  // ==================== CONSISTENCY BADGES ====================
  {
    code: 'week_warrior',
    name: 'Week Warrior',
    description: 'Play 3 rounds in one week',
    icon: '📅',
    category: 'consistency',
    points: 20,
    sortOrder: 120,
  },
  {
    code: 'monthly_regular',
    name: 'Monthly Regular',
    description: 'Play 5 rounds in one month',
    icon: '📆',
    category: 'consistency',
    points: 25,
    sortOrder: 121,
  },
  {
    code: 'streak_starter',
    name: 'Streak Starter',
    description: 'Play 3 weeks in a row',
    icon: '🔥',
    category: 'consistency',
    points: 25,
    sortOrder: 122,
  },
  {
    code: 'weekend_golfer',
    name: 'Weekend Golfer',
    description: 'Play 5 rounds on weekends',
    icon: '🌅',
    category: 'consistency',
    points: 25,
    threshold: 5,
    sortOrder: 123,
  },

  // ==================== APP FEATURES BADGES ====================
  {
    code: 'gps_user',
    name: 'GPS User',
    description: 'Use the course map feature',
    icon: '🗺️',
    category: 'app',
    points: 15,
    sortOrder: 130,
  },
  {
    code: 'stat_tracker',
    name: 'Stat Tracker',
    description: 'View your statistics page',
    icon: '📊',
    category: 'app',
    points: 10,
    sortOrder: 131,
  },
  {
    code: 'guide_reader',
    name: 'Guide Reader',
    description: 'Visit the User Guide',
    icon: '📖',
    category: 'app',
    points: 10,
    sortOrder: 132,
  },

  // ==================== SOCIAL BADGES ====================
  {
    code: 'group_member',
    name: 'Team Player',
    description: 'Join a golfer group',
    icon: '👥',
    category: 'social',
    points: 10,
    threshold: 1,
    sortOrder: 60,
  },
  {
    code: 'group_leader',
    name: 'Group Captain',
    description: 'Create a golfer group',
    icon: '👨‍✈️',
    category: 'social',
    points: 30,
    threshold: 1,
    sortOrder: 61,
  },
  {
    code: 'friendly_golfer',
    name: 'Friendly Golfer',
    description: 'Play with 3 different partners',
    icon: '🤝',
    category: 'social',
    points: 15,
    threshold: 3,
    sortOrder: 62,
  },
  {
    code: 'group_player',
    name: 'Group Player',
    description: 'Play 3 rounds with group members',
    icon: '👥',
    category: 'social',
    points: 20,
    threshold: 3,
    sortOrder: 63,
  },
  {
    code: 'welcoming',
    name: 'Welcoming',
    description: 'Play with a first-time user',
    icon: '🎉',
    category: 'social',
    points: 20,
    sortOrder: 64,
  },

  // ==================== SPECIAL BADGES ====================
  {
    code: 'early_bird',
    name: 'Early Bird',
    description: 'Complete a round before 11 AM',
    icon: '🌅',
    category: 'special',
    points: 20,
    sortOrder: 70,
  },
  {
    code: 'sunset_golfer',
    name: 'Sunset Golfer',
    description: 'Complete a round after 6 PM',
    icon: '🌇',
    category: 'special',
    points: 20,
    sortOrder: 71,
  },
];

async function main() {
  console.log('Seeding achievements...');

  for (const achievement of achievements) {
    await prisma.achievement.upsert({
      where: { code: achievement.code },
      update: achievement,
      create: achievement,
    });
  }

  console.log(`Seeded ${achievements.length} achievements`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
